---
- name: Install IPTables services
  dnf: name=iptables-services state=latest
  notify:
   - Enable IPTables
   - Start IPTables
- name: Configure IPTables
  template: src=iptables.j2 dest=/etc/sysconfig/iptables
  notify: Restart IPTables
