---
- include_vars: passwords_vault.yml

- name: delete old serivce files
  file: path=/opt/MonitronManagement state=absent

- name: upload management service
  unarchive: src=MonitronManagement.tar.gz dest=/opt
  notify:
   - restart Management Server

- name: create management user
  user: name=monitron system=yes createhome=no home=/opt/MonitronManagement shell=/sbin/nologin comment="Monitron Management"

- name: install service file
  copy: src=monitron-management.service dest=/etc/systemd/system/
  notify:
   - start Management server

- name: enable Management server
  service: name=monitron-management enabled=yes

- name: creates configuration directory
  file: path=/etc/monitron state=directory group=monitron mode=0755

- name: copy configuration
  template: src=management.conf.j2 dest=/etc/monitron/management.conf group=monitron mode=0640
  notify:
   - restart Management server

- name: copy initial data store
  template: src=datastore.json.j2 dest=/etc/monitron/datastore.json group=monitron mode=0640
  notify:
   - restart Management server
