---
- hosts: worker_servers
  tasks:
   - name: Install Docker
     dnf: name=docker state=latest
     notify:
      - Enable Docker Service
      - Start Docker Service

   - name: Install Docker Client
     dnf: name=docker-client state=latest

   - name: Force Service Restart
     meta: flush_handlers

   - name: Upload node container image
     copy: src=node-container/node-container-image.tar dest=/

   - name: Load image into docker
     raw: docker load -i /node-container-image.tar

   - name: Delete image tar
     file: path=/node-container-image.tar state=absent

  handlers:
   - name: Enable Docker Service
     service: name=docker enabled=yes
   - name: Start Docker Service
     service: name=docker state=started
   - name: Restart Docker Service
     service: name=docker state=restarted
