---
- name: start Docker service
  service: name=docker state=started

- name: restart Docker service
  service: name=docker state=restarted

- name: reloading systemd daemon information
  shell: systemctl daemon-reload
