---
- include_vars: passwords_vault.yml

- name: install MongoDB server
  dnf: name=mongodb-server state=latest
  notify:
   - start MongoDB server

- name: enable MongoDB Server
  service: name=mongod enabled=yes


- name: configure MongoDB server
  copy:
   src: "mongod.conf"
   dest: "/etc/mongod.conf"
   mode: 0644
   owner: root
   group: root
  notify:
   - restart MongoDB server

- name: install MongoDB client
  dnf: name=mongodb state=latest

- name: force service restart
  meta: flush_handlers

- name: run DB initialization script
  become: yes
  become_user: mongodb
  script: "./db_init.sh '{{monitron_admin_password}}'"
