- name: install Mono repository keys
  raw: rpm --import "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF"

- name: install Mono repository
  raw: dnf config-manager --add-repo http://download.mono-project.com/repo/centos/

- name: install Mono
  dnf: name=mono-complete state=latest
