---
- include_vars: cert_vault.yml
- include_vars: passwords_vault.yml

- name: clean log files ( remove once enough time has passed )
  file: name=/var/log/prosody state=absent

- name: install Prosody
  dnf: name=prosody state=latest
  notify:
   - start Prosody

- name: enable Prosody
  service: name=prosody enabled=yes

- name: upload Prosody server configuration
  template: src=prosody.cfg.lua.j2 dest={{prosody_conf_path}} mode=640 owner=root group=prosody
  notify:
   - restart Prosody

- name: upload Monitron site configuration
  template: src=prosody_site.cfg.lua.j2 dest={{monitron_site_conf_path}} mode=640 owner=root group=prosody
  notify:
   - restart Prosody

- name: upload Monitron site cert (crt)
  copy:
   content: "{{ monitron_cert_crt }}"
   dest: "{{pki_path}}/{{domain_name}}.crt"
   mode: 0644
   owner: root
   group: root
  notify:
   - restart Prosody

- name: upload Monitron site cert (key)
  copy:
   content: "{{ monitron_cert_key }}"
   dest: "{{pki_path}}/{{domain_name}}.key"
   mode: 0640
   owner: root
   group: prosody
  notify:
   - restart Prosody

- name: upload Monitron site cert (cnf)
  copy:
   content: "{{ monitron_cert_cnf }}"
   dest: "{{pki_path}}/{{domain_name}}.cnf"
   mode: 0640
   owner: root
   group: prosody
  notify:
   - restart Prosody

- name: upload Monitron Ad-Hoc module
  copy: src=mod_monitron_adhoc.lua dest={{prosody_module_path}} mode=644 owner=root group=root
  notify:
   - restart Prosody

- name: upload json module
  copy: src=dkjson.lua dest={{prosody_lib_path}} mode=644 owner=root group=root
  notify:
   - restart Prosody

- name: upload Boty Auth module
  copy: src=mod_auth_boty.lua dest={{prosody_module_path}} mode=644 owner=root group=root
  notify:
   - restart Prosody

- name: create Monitron admin
  prosody_adduser: jid=monitron_admin@{{domain_name}} password={{monitron_admin_password}}

- name: create Server admin
  prosody_adduser: jid=admin@{{domain_name}} password={{admin_password}}

- name: create Management user
  prosody_adduser: jid=themanagement@{{domain_name}} password={{monitron_management_password}}

- name: create Local Monitor user
  prosody_adduser: jid=local_monitor@{{domain_name}} password={{local_monitor_password}}
