---
- name: install packages for ansible support
  raw: dnf -y install python python-dnf

- name: install Ansible dependencies
  dnf: name=libselinux-python state=latest

- name: limit journald size
  template: src=journald.conf.j2 dest=/etc/systemd/journald.conf
  notify:
    - vacuume logs
