---
- include_vars: passwords_vault.yml

- name: delete old serivce files
  file: path=/opt/MonitronLocalMonitor state=absent

- name: upload local monitor service
  unarchive: src=MonitronLocalMonitor.tar.gz dest=/opt
  notify:
   - restart local monitor

- name: create management user
  user: name=monitron system=yes createhome=no home=/opt/MonitronLocalMonitor shell=/sbin/nologin comment="Monitron Local Monitor"

- name: install service file
  template: src=monitron-local-monitor.service.j2 dest=/etc/systemd/system/monitron-local-monitor.service
  notify:
   - start local monitor

- name: enable local monitor
  service: name=monitron-local-monitor enabled=yes

- name: creates configuration directory
  file: path=/etc/monitron state=directory group=monitron mode=0755

- name: copy configuration
  template: src=localmonitor.conf.j2 dest=/etc/monitron/localmonitor.conf group=monitron mode=0640
  notify:
   - restart local monitor

- name: copy initial data store
  template: src=datastore.json.j2 dest=/etc/monitron/localmonitor.ds.json group=monitron mode=0640
  notify:
   - restart local monitor
