---
- name: create api server user
  user: name=boty_api system=yes createhome=no home=/opt/Boty.Api shell=/sbin/nologin comment="Boty API Server"

- name: upload api server
  synchronize: src=../../Boty.Api dest=/opt/ recursive=yes delete=yes
  notify:
    - restart boty api server

- name: set upload dir permissions
  file: name=/opt/Boty.Api/uploads owner=boty_api group=boty_api

- name: configure api server
  template: src=options.js.j2 dest=/opt/Boty.Api/options.js
  notify:
    - restart boty api server

- name: set up nodejs repo
  raw: dnf copr enable nibbler/nodejs -y

- name: install nodejs
  dnf: name=nodejs state=latest

- name: install npm
  dnf: name=npm state=latest

- name: install service file
  template: src=boty-api.service.j2 dest=/etc/systemd/system/boty-api.service

- name: enable boty api server
  service: name=boty-api enabled=yes

- name: start boty api server
  service: name=boty-api state=started
